# Generated by Django 5.0.6 on 2024-05-30 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notestatus_note_duedate'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.notestatus'),
        ),
    ]
